### ISSUE TITLE
Erroneous files

### ISSUE THREAD

**Issue by johnbieren** [jmartuccelli/ugene#3]
What is qt-4.8.7-2.el7.aarch64.rpm doing here? It is not even an x86_64 rpm. And why is there a repomd.xml outside of a repodata/ dir?

**Comment by john-martuccelli** [comment]
thought a new repomd.xml would fix the broken one, thanks github. delted since it does not.

**Comment by johnbieren** [comment]
I see. repomd.xml has to always be in a repodata/ directory though
